import hashlib
import json
import re
from typing import Any

from anthropic import APIStatusError, Anthropic
from fastapi import HTTPException

from .cache import get_cache, set_cache
from .config import settings
from .database import save_scored_lead
from .schemas import AIScore, LeadIn, ScoredLead
from .scoring_helpers import normalize_number


def _text(value: Any, fallback: str = "Unknown") -> str:
    if value is None or value == "":
        return fallback
    return str(value)


def lead_cache_key(lead: dict[str, Any]) -> str:
    identity = (
        lead.get("website")
        or lead.get("domain")
        or lead.get("email")
        or lead.get("company")
        or lead.get("name")
        or json.dumps(lead, sort_keys=True)
    )
    digest = hashlib.sha256(str(identity).lower().encode("utf-8")).hexdigest()
    return f"lead-score:{digest}"


def _fallback_score(lead: dict[str, Any]) -> dict[str, Any]:
    revenue = normalize_number(lead.get("revenue") or lead.get("annual_revenue"))
    employees = normalize_number(lead.get("employees") or lead.get("employee_count"))
    description = " ".join(
        _text(lead.get(key), "")
        for key in ("industry", "sector", "title", "description", "notes")
    ).lower()

    revenue_fit = 85 if 1_000_000 <= revenue <= 20_000_000 else 55 if revenue else 35
    size_fit = 90 if 5 <= employees <= 150 else 62 if employees <= 500 else 42
    industry_fit = 78
    if re.search(r"software|healthcare|services|logistics|manufacturing|b2b", description):
        industry_fit = 86
    if re.search(r"creative|agency|restaurant|retail", description):
        industry_fit = 54

    owner_reachability = 35
    if lead.get("email_valid"):
        owner_reachability += 25
    elif lead.get("email_syntax_valid"):
        owner_reachability += 10
    if lead.get("phone"):
        owner_reachability += 15
    if lead.get("owner") or lead.get("founder") or re.search(r"founder|owner", description):
        owner_reachability += 20
    owner_reachability = min(owner_reachability, 100)

    growth_signals = 45
    if re.search(r"growing|expanded|hiring|new|launch|automation|ai|scale", description):
        growth_signals = 78

    overall = round(
        revenue_fit * 0.25
        + industry_fit * 0.2
        + size_fit * 0.2
        + owner_reachability * 0.2
        + growth_signals * 0.15
    )
    tier = "A" if overall >= 80 else "B" if overall >= 65 else "C" if overall >= 45 else "D"

    return {
        "overall_score": overall,
        "dimensions": {
            "revenue_fit": revenue_fit,
            "industry_fit": industry_fit,
            "size_fit": size_fit,
            "owner_reachability": owner_reachability,
            "growth_signals": growth_signals,
        },
        "tier": tier,
        "acquisition_thesis": "This score was generated by the local development scorer because Claude fallback mode is enabled. Use it only for testing persistence and caching, not production lead decisions.",
        "key_risks": ["Development fallback score", "No Claude reasoning was used"],
        "key_opportunities": ["Validate backend persistence", "Validate Redis cache behavior"],
        "recommended_action": "Pursue" if tier in ("A", "B") else "Monitor",
        "estimated_ev_range": "Unknown",
        "fit_tags": ["dev-fallback", f"tier-{tier.lower()}"],
    }


def _prompt(lead: dict[str, Any]) -> str:
    return f"""You are an M&A analyst at a private equity firm focused on acquiring small-to-mid-size businesses using an ETA/search fund model.

Company data:
- Name: {_text(lead.get("company") or lead.get("name"))}
- Industry: {_text(lead.get("industry") or lead.get("sector"))}
- Location: {_text(lead.get("location") or lead.get("city") or lead.get("country"))}
- Employees: {_text(lead.get("employees") or lead.get("employee_count"))}
- Revenue: {_text(lead.get("revenue") or lead.get("annual_revenue"))}
- Normalized revenue range: {_text(lead.get("revenue_range"))}
- Website: {_text(lead.get("website") or lead.get("domain"))}
- Owner/Contact: {_text(lead.get("owner") or lead.get("contact") or lead.get("founder"))}
- Email: {_text(lead.get("email"))}
- Email validation: syntax={lead.get("email_syntax_valid", False)}, mx={lead.get("email_mx_valid", False)}
- Phone: {_text(lead.get("phone"))}
- Description: {_text(lead.get("description") or lead.get("notes"), "N/A")}

Respond only with valid JSON matching this shape:
{{
  "overall_score": 0,
  "dimensions": {{
    "revenue_fit": 0,
    "industry_fit": 0,
    "size_fit": 0,
    "owner_reachability": 0,
    "growth_signals": 0
  }},
  "tier": "A",
  "acquisition_thesis": "Two plain-English sentences.",
  "key_risks": ["risk"],
  "key_opportunities": ["opportunity"],
  "recommended_action": "Pursue",
  "estimated_ev_range": "Unknown",
  "fit_tags": ["tag"]
}}

Scoring guidance:
- revenue_fit: $1M-$20M revenue is ideal.
- industry_fit: stable, cash-flowing, non-cyclical businesses score higher.
- size_fit: 5-150 employees is ideal.
- owner_reachability: direct owner/founder contact info scores higher.
- growth_signals: expansion, hiring, automation, or AI leverage score higher.
"""


def _score_with_claude(lead: dict[str, Any]) -> dict[str, Any]:
    if not settings.anthropic_api_key:
        if settings.allow_fallback_scoring:
            return _fallback_score(lead)
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY is not configured and no cached score exists for this lead.",
        )
    try:
        client = Anthropic(api_key=settings.anthropic_api_key)
        response = client.messages.create(
            model=settings.anthropic_model,
            max_tokens=1_200,
            messages=[{"role": "user", "content": _prompt(lead)}],
        )
    except APIStatusError as error:
        message = error.response.text
        if "credit balance is too low" in message.lower():
            if settings.allow_fallback_scoring:
                return _fallback_score(lead)
            raise HTTPException(
                status_code=402,
                detail=(
                    "Anthropic credit balance is too low. Add credits in Anthropic "
                    "Plans & Billing, or set ALLOW_FALLBACK_SCORING=true for local testing."
                ),
            ) from error
        raise HTTPException(
            status_code=error.status_code,
            detail=f"Anthropic API error: {message}",
        ) from error

    text = next((block.text for block in response.content if block.type == "text"), "{}")
    clean = text.replace("```json", "").replace("```", "").strip()
    return json.loads(clean)


def _to_frontend_shape(lead: dict[str, Any], score: AIScore, cached: bool) -> ScoredLead:
    company = lead.get("company") or lead.get("name") or "lead"
    identity = lead.get("website") or lead.get("email") or company
    dimensions = score.dimensions

    frontend_lead = {
        **lead,
        "company": company,
        "contact": lead.get("contact") or lead.get("owner") or lead.get("founder") or "Unknown contact",
        "title": lead.get("title") or "Unknown role",
        "industry": lead.get("industry") or lead.get("sector") or "Unknown",
        "location": lead.get("location") or lead.get("city") or lead.get("country") or "Unknown",
        "website": lead.get("website") or lead.get("domain") or "",
        "email": lead.get("email") or "",
        "employees": normalize_number(lead.get("employees") or lead.get("employee_count")),
        "revenue": normalize_number(lead.get("revenue") or lead.get("annual_revenue")),
        "notes": lead.get("notes") or lead.get("description") or "",
    }

    return ScoredLead(
        id=hashlib.sha1(str(identity).lower().encode("utf-8")).hexdigest(),
        score=score.overall_score,
        fit=round((dimensions.revenue_fit + dimensions.industry_fit + dimensions.size_fit) / 3),
        intent=round((dimensions.owner_reachability + dimensions.growth_signals) / 2),
        estimatedValue=max(5_000, round(frontend_lead["revenue"] * 0.35)) if frontend_lead["revenue"] else 0,
        reasons=score.fit_tags or [score.acquisition_thesis],
        nextAction=score.recommended_action,
        aiScore=score,
        cached=cached,
        lead=frontend_lead,
    )


async def score_lead(lead: LeadIn | dict[str, Any]) -> ScoredLead:
    lead_dict = lead if isinstance(lead, dict) else lead.model_dump(exclude_none=True)
    cache_key = lead_cache_key(lead_dict)

    cached_score = await get_cache(cache_key)
    if cached_score:
        score = AIScore.model_validate(cached_score)
        await save_scored_lead(lead_dict, score.model_dump(), cache_key, cache_hit=True)
        return _to_frontend_shape(lead_dict, score, cached=True)

    raw_score = _score_with_claude(lead_dict)
    score = AIScore.model_validate(raw_score)
    score_dict = score.model_dump()

    await set_cache(cache_key, score_dict)
    await save_scored_lead(lead_dict, score_dict, cache_key, cache_hit=False)

    return _to_frontend_shape(lead_dict, score, cached=False)
